name: Deploy Documentation

on:
  push:
    branches:
      - main 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential doxygen graphviz libexiv2-dev

      - name: Configure CMake
        run: |
          cmake --preset release-shared -DBUILD_DOCS=ON

      - name: Build Doxygen Documentation
        run: |
          cmake --build --preset release-shared --target docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          
          path: 'out/release-shared/docs/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4